---
title: "Lab10 - Project data overview"
output: html_document
date: '2022-04-07'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#**Group 6:** 

- Joachim Breitenstein
- Mathias Rahbek-Borre
- William Hagedorn-Rasmussen
- Esben Vestergaard Øyan
- Eskild Fisker Angen 

#**Link to data:** 

- https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.88896

#**Brief description of data:** 

10 variables, 393 observations. Data from article: "Peripheral blood mitochondrial DNA copy number is associated with prostate cancer risk and tumor burden".
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0109470 


#**Preliminary outline for project:** 

* Recreation of visualizations illustrated in article.

* Remove non-assayable datapoints.

* covariation(?) on PBL and PC.

* Daily fat intake vs smoking as contributor to PC (covarianse/residual analysis)

* Split DFT, Smoking History and BMI off, examine and join back in.

* PC, BMI and age in relation to each other. (maybe stratify on smoking habits).

* Find clear description of TNM stage and incorporate in manipulaitons? (What does TNM, AJCC and mtDNA signify? - correlations?)

* Categorize participants based on BMI - maybe also on other factors?


