library("tidyverse")
library("patchwork")
library("ggsignif")
library("rmarkdown")
library("knitr")

# Run all scripts ---------------------------------------------------------
source("R/01_load.R")
source("R/02_clean.R")
source("R/03_augment.R")
source("R/04_test_for_outliers.R")
source("R/05_PCA_model.R")
source("R/06_logistic_regression.R")
source("R/07_boxplot_BMI_Dfi_class.R")
source("R/08_article_visualization.R")
source("R/09_mtDNA_vs_PSA.R")
source("R/10_Boxplot_PSA.R")
source("R/11_other_correlations.R")
source("R/12_correlation_analysis.R")
rmarkdown::render("docs/Slides.Rmd")
browseURL("docs/Slides.html")

